# Generated by Django 5.2 on 2025-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAssignApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
