# Generated by Django 5.2 on 2025-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAssignApp', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='TO DO', max_length=50),
        ),
    ]
